const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../PrilavokPOS/Web/js/features/loyalty.js'),'utf8');
const c={};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('function customerPhoneDigits('),html.indexOf('async function customerSearchChanged(')),c);
test('customer phone accepts manual suffix or pasted Belarus number',()=>{assert.equal(c.customerPhoneDigits('29 123 45 67'),'291234567');assert.equal(c.customerPhoneDigits('+375 (29) 123-45-67'),'291234567');assert.equal(c.customerPhoneDigits('375291234567'),'291234567');assert.equal(c.customerPhoneDigits('abc29'),'29');assert.equal(c.customerPhoneDigits(''),'');assert.equal(c.customerPhoneDigits('29123456789'),'291234567')});
test('picker starts at four digits and keeps only matching phone prefixes',async()=>{
 let calls=0,query;const el={innerHTML:'',querySelectorAll:()=>[]},input={value:''};const ctx={document:{getElementById:id=>id==='customer-search-results'?el:input},searchCustomers:async q=>{calls++;query=q;return [{id:'1',name:'Анна',normalized_phone:'+375291234567'},{id:'2',name:'Иван',normalized_phone:'+375331234567'}]},escapeHtml:String,escapeAttr:String};vm.createContext(ctx);vm.runInContext('let customerSearchSeq=0;'+html.slice(html.indexOf('function customerPhoneDigits('),html.indexOf('async function selectCustomer(')),ctx);await ctx.customerSearchChanged('291');assert.equal(calls,0);await ctx.customerSearchChanged('2912');assert.equal(query,'+3752912');assert.match(el.innerHTML,/Анна/);assert.doesNotMatch(el.innerHTML,/Иван/);
});
function customerFixture(){
 const context={state:{customer:{id:'c',name:'Анна',phone:'+375291234567',address:'Адрес доставки'},cart:[{productId:'p',qty:2}],loyaltyPrograms:[{id:'l'}],loyaltyRedemptions:{l:1}},saveCurrentOrderSession(){context.saved=JSON.parse(JSON.stringify(context.state.customer))},closeModal(){},render(){},flash(){}};
 vm.createContext(context);vm.runInContext('let customerSearchSeq=0;'+html.slice(html.indexOf('async function loadCustomerLoyalty('),html.indexOf('function openOrderCustomer('))+html.slice(html.indexOf('function removeOrderCustomer('),html.indexOf('function openCreateCustomer(')),context);return context;
}
test('detach clears customer and rewards, persists session and preserves cart and delivery address',()=>{const c=customerFixture(),cart=c.state.cart;c.removeOrderCustomer();assert.equal(c.state.customer.id,undefined);assert.equal(c.saved.name,'');assert.equal(c.saved.phone,'');assert.equal(c.saved.address,'Адрес доставки');assert.equal(c.state.cart,cart);assert.equal(c.state.loyaltyPrograms.length,0);assert.equal(Object.keys(c.state.loyaltyRedemptions).length,0)});
test('late loyalty response cannot attach a removed customer again',async()=>{const c=customerFixture();let resolve;c.loyaltyApi=()=>new Promise(r=>resolve=r);const pending=c.loadCustomerLoyalty('c');c.removeOrderCustomer();resolve({customer:{id:'c',name:'Анна',normalized_phone:'+375291234567'},programs:[{id:'l'}]});await pending;assert.equal(c.state.customer.id,undefined);assert.equal(c.state.loyaltyPrograms.length,0)});
