const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const html=fs.readFileSync(path.join(__dirname,"../PrilavokPOS/pos.html"),"utf8");
const loyalty=fs.readFileSync(path.join(__dirname,"../PrilavokPOS/Web/js/features/loyalty.js"),"utf8");
const payment=fs.readFileSync(path.join(__dirname,"../PrilavokPOS/Web/js/features/payment.js"),"utf8");
const receipts=fs.readFileSync(path.join(__dirname,"../PrilavokPOS/Web/js/features/receipts.js"),"utf8");
test("POS exposes customer search and single reward loyalty balance",()=>{assert.match(loyalty,/openCustomerPicker/);assert.match(loyalty,/\/api\/customers\/search/);assert.match(loyalty,/\/loyalty/);assert.match(loyalty,/Прогресс:/);assert.match(loyalty,/Подарок:/)});
test('customer picker uses compact header actions and numeric phone input',()=>{assert.match(loyalty,/customer-picker-heading[\s\S]+customer-picker-close[\s\S]+Клиент заказа[\s\S]+customer-picker-add/);assert.match(loyalty,/id="customer-search" type="tel" inputmode="numeric"/);assert.doesNotMatch(loyalty,/Поиск начинается после четырёх цифр номера/);assert.doesNotMatch(loyalty,/customer-picker-actions/);assert.doesNotMatch(loyalty,/getElementById\('customer-search'\)\?\.focus/)});
test("loyalty is published only from finalized payment path",()=>{const finalize=payment.slice(payment.indexOf("function finalizePayment"),payment.indexOf("function openCashModal"));assert.match(finalize,/publishPaidOrderLoyalty\(order\)/);assert.match(payment,/loyaltySync=\{status:'pending'/)});
test("reward selection is capped at one active gift",()=>{assert.match(loyalty,/Number\(state\.loyaltyRedemptions\?\.\[program\.id\]\)>0\?1:0/);assert.match(loyalty,/Использовать подарок/);assert.doesNotMatch(loyalty,/Array\.from\(\{length:Number\(p\.rewards\)\}/)});

test("reward discount is separated from product base price",()=>{assert.match(loyalty,/function loyaltyRewardDiscount/);assert.match(loyalty,/Программа лояльности/);assert.match(html,/Math\.max\(0,cartSubtotal\(\).*loyaltyRewardDiscount\(\)/s)});
test('customer modal distinguishes loading, empty and failed loyalty states',()=>{assert.match(loyalty,/Загружаем программы/);assert.match(loyalty,/Для клиента пока нет активных программ/);assert.match(loyalty,/Не удалось загрузить программы/);assert.match(loyalty,/loyaltyCustomerId/)});
test('paid receipt stores and renders product and loyalty discounts',()=>{assert.match(payment,/loyaltyDiscount:loyaltyReceipt\.discount/);assert.match(payment,/loyaltyProgramsApplied/);assert.match(payment,/productDiscountTotal/);assert.match(payment,/Лояльность ·/);assert.match(payment,/Скидки на товары/)});
test("paid loyalty has ordered reconnect retry and refund reversal",()=>{assert.match(loyalty,/function retryPendingLoyalty/);assert.match(loyalty,/function settleReturnedOrderLoyalty/);assert.match(loyalty,/\/api\/loyalty\/reversal/);assert.match(receipts,/processFullReturn[\s\S]*settleReturnedOrderLoyalty\(committedOrder\)/)});
test("admin panel exposes customers and loyalty programs",()=>{assert.match(loyalty,/openCustomersAdmin/);assert.match(loyalty,/openLoyaltyAdmin/);assert.match(loyalty,/Новая программа/);assert.match(loyalty,/Клиенты/)});
test('offline POS keeps normal payment available while reward redemption requires server confirmation',()=>{assert.match(payment,/Продажу и оплату можно продолжить без интернета/);assert.match(payment,/Продолжить без подарка/);assert.match(payment,/revalidateSelectedLoyaltyReward/);});
test('pending loyalty reversals retry after reconnect',()=>{assert.match(loyalty,/loyaltyReversal\?\.status==='pending'/);assert.match(loyalty,/void settleReturnedOrderLoyalty\(order\)/);});
